-- CreateTable
CREATE TABLE "product" (
    "id" TEXT NOT NULL,
    "sku" TEXT,
    "category_id" TEXT NOT NULL,
    "category_name" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "price" INTEGER NOT NULL,
    "discounted_price" INTEGER,
    "stock_quantity" INTEGER NOT NULL DEFAULT 0,
    "status" TEXT NOT NULL DEFAULT 'SALE',
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "description" TEXT NOT NULL DEFAULT '',
    "detail_html" TEXT NOT NULL DEFAULT '',
    "images" TEXT[],
    "brand" TEXT NOT NULL,
    "manufacturer_name" TEXT NOT NULL DEFAULT '',
    "model_name" TEXT NOT NULL DEFAULT '',
    "tags" TEXT[],
    "delivery_fee" INTEGER NOT NULL DEFAULT 0,
    "return_fee" INTEGER NOT NULL DEFAULT 0,
    "exchange_fee" INTEGER NOT NULL DEFAULT 0,
    "sort_order" INTEGER NOT NULL,
    "origin_product_no" TEXT NOT NULL,
    "channel_product_no" TEXT NOT NULL,
    "naver_category_id" TEXT NOT NULL,
    "naver_whole_category_id" TEXT NOT NULL,
    "smartstore_url" TEXT NOT NULL,
    "registered_at" TIMESTAMP(3) NOT NULL,
    "channel_modified_at" TIMESTAMP(3) NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "product_pkey" PRIMARY KEY ("id")
);
